package com.example.smartcard.localization

import androidx.compose.runtime.staticCompositionLocalOf

data class AppStrings(
    val email: String,
    val password: String,
    val login: String,
    val signUp: String,
    val language: String,
    val chooseLanguage: String,
    val personalData: String,
    val notifications: String,
    val myPurchases: String,
    val myCards: String,
    val exit: String,
    val user: String,
    val noEmail: String,
    val ok: String,
    val info: String,
    val loading: String,
    val loginWithGoogle: String,
    val dontHaveAccount: String,
    val cantLogin: String,
    val emailPlaceholder: String,
    val passwordHint: String,
    val goodAfternoon: String,
    val welcomeTo: String,
    val smart: String,
    val shopping: String,
    val cart: String,
    val scanProduct: String,
    val scannerCount: String,
    val receiptTaxInvoice: String,
    val detectedCount: String,
    val productsPurchased: String,
    val back: String,
    val cameraPointToProduct: String,
    val cameraPermissionRequired: String,
    val productLabel: String,
    val cartConnected: String,
    val cartConnectedDesc: String,
    val cartId: String,
    val notAvailable: String,
    val backToHome: String,
    val shoppingCartTitle: String,
    val total: String,
    val currency: String,
    val goToPayment: String,
    val paymentFailed: String,
    val userNotLoggedIn: String,
    val receiptNotFound: String,
    val failedToLoadReceipt: String,
    val errorLabel: String,
    val shopName: String,
    val receiptIdLabel: String,
    val timeLabel: String,
    val itemsLabel: String,
    val purchaseNotFound: String,
    val failedToLoadPurchase: String,
    val purchaseInformation: String,
    val locationLabel: String,
    val locationValue: String,
    val purchaserLabel: String,
    val unknown: String,
    val dateTimeLabel: String,
    val yourPurchase: String,
    val paid: String,
    val amount: String,
    val tenge: String,
    val history: String,
    val orderCompleted: String,
    val noPurchases: String,
    val connectedTo: String,
    val successful: String,
    val paymentSuccessDesc: String,
    val purchaseId: String,
    val downloadReceipt: String,
    val receiptUnavailable: String,
    val onboardingStepScanCartQr: String,
    val onboardingStepAutoAddProducts: String,
    val onboardingStepInstantPay: String,
    val onboardingSubtitleProductFlow: String,
    val skip: String,
    val next: String,
    val start: String,
    val welcomeBack: String,
    val loginSubtitleSyncCart: String,
    val createAccount: String,
    val signUpSubtitleEnterDetails: String,
    val signUpWithGoogle: String,
    val agreeWith: String,
    val terms: String,
    val privacy: String,
    val alreadyHaveAccount: String,
    val validationNameRequired: String,
    val validationEnterValidEmail: String,
    val validationPasswordTooShort: String,
    val validationPasswordsDoNotMatch: String,
    val validationAcceptTerms: String,
    val homeHello: String,
    val scanCartQr: String,
    val continueShopping: String,
    val sessionStatusLabel: String,
    val sessionStateWaiting: String,
    val sessionStateConnected: String,
    val sessionStateShopping: String,
    val sessionStateFinished: String,
    val purchases: String,
    val receipts: String,
    val noPurchasesYet: String,
    val selectLanguage: String,
    val cancel: String,
    val fullName: String,
    val fullNamePlaceholder: String,
    val confirmPassword: String,
    val onboardingTitle1: String,
    val onboardingTitle2: String,
    val onboardingTitle3: String,
    val notificationsTitle: String,
    val notifPromoTitle: String,
    val notifPromoSubtitle: String,
    val notifNewsTitle: String,
    val notifNewsSubtitle: String,
    val couldNotLoadHistory: String,
    val historyAccessTemporarilyUnavailable: String,
    val historyCheckConnectionAndRetry: String,
    val orderNumberPrefix: String,
    val langKazakh: String,
    val langRussian: String,
    val langEnglish: String,
    val chooseLanguageSubtitle: String,
    val productBarcodeMismatch: String,
    val legacyQrNotSupported: String,
    val invalidCartQr: String,
    val connectedToCart: String,
    val productNotFoundForBarcode: String,
    val addedPrefix: String,
)

fun provideStrings(lang: String): AppStrings {
    return when (lang) {

        "ru" -> AppStrings(
            email = "Электронная почта",
            password = "Пароль",
            login = "Войти",
            signUp = "Зарегистрироваться",
            language = "Язык",
            chooseLanguage = "Выберите язык приложения",
            personalData = "Личные данные",
            notifications = "Уведомления",
            myPurchases = "Мои покупки",
            myCards = "Мои карты",
            exit = "Выйти",
            user = "Пользователь",
            noEmail = "Нет email",
            ok = "ОК",
            info = "Информация",
            loading = "Загрузка...",
            loginWithGoogle = "Войти через Google",
            dontHaveAccount = "Нет аккаунта?",
            cantLogin = "Не удаётся войти?",
            emailPlaceholder = "name@email.com",
            passwordHint = "Минимум 8 символов",
            goodAfternoon = "Добрый день 👋🏻",
            welcomeTo = "Добро пожаловать в",
            smart = "умную",
            shopping = "покупательскую",
            cart = "корзину",
            scanProduct = "Сканировать товар",
            scannerCount = "384 сканирований",
            receiptTaxInvoice = "Чек / налоговая накладная",
            detectedCount = "Обнаружено 23",
            productsPurchased = "Купленные товары",
            back = "Назад",
            cameraPointToProduct = "Наведите камеру на товар",
            cameraPermissionRequired = "Требуется разрешение на камеру",
            productLabel = "Товар",
            cartConnected = "Тележка подключена",
            cartConnectedDesc = "Ваш телефон подключен к тележке.",
            cartId = "ID тележки",
            notAvailable = "Недоступно",
            backToHome = "На главную",
            shoppingCartTitle = "Корзина покупок 🛒",
            total = "Итого",
            currency = "TG",
            goToPayment = "Перейти к оплате",
            paymentFailed = "Оплата не удалась",
            userNotLoggedIn = "Пользователь не вошёл в систему",
            receiptNotFound = "Чек не найден",
            failedToLoadReceipt = "Не удалось загрузить чек",
            errorLabel = "Ошибка",
            shopName = "MAGNUM SHOPPING CENTER",
            receiptIdLabel = "ID чека",
            timeLabel = "Время",
            itemsLabel = "товаров",
            purchaseNotFound = "Покупка не найдена",
            failedToLoadPurchase = "Не удалось загрузить покупку",
            purchaseInformation = "Информация о покупке",
            locationLabel = "Местоположение:",
            locationValue = "Алматы, Казахстан",
            purchaserLabel = "Покупатель:",
            unknown = "Неизвестно",
            dateTimeLabel = "Дата и время:",
            yourPurchase = "Ваша покупка:",
            paid = "Оплачено",
            amount = "Сумма",
            tenge = "₸",
            history = "История",
            orderCompleted = "Заказы завершены",
            noPurchases = "Покупок пока нет",
            connectedTo = "Подключено к",
            successful = "Успешно ✅",
            paymentSuccessDesc = "Ваш платеж успешно завершён",
            purchaseId = "ID покупки",
            downloadReceipt = "Скачать чек",
            receiptUnavailable = "⚠️ Чек недоступен. Проверьте сохранение purchase_id",
            onboardingStepScanCartQr = "Сканируйте QR на тележке, чтобы начать сессию",
            onboardingStepAutoAddProducts = "Товары добавляются автоматически во время покупок",
            onboardingStepInstantPay = "Оплачивайте мгновенно без очереди",
            onboardingSubtitleProductFlow = "Покупательский путь SmartCart от подключения до оплаты.",
            skip = "Пропустить",
            next = "Далее",
            start = "Начать",
            welcomeBack = "С возвращением",
            loginSubtitleSyncCart = "Войдите, чтобы синхронизировать тележку и покупки",
            createAccount = "Создать аккаунт",
            signUpSubtitleEnterDetails = "Пожалуйста, введите ваши данные",
            signUpWithGoogle = "Зарегистрироваться через Google",
            agreeWith = "Я согласен с",
            terms = "Условиями",
            privacy = "Конфиденциальностью",
            alreadyHaveAccount = "Уже есть аккаунт?",
            validationNameRequired = "Имя обязательно",
            validationEnterValidEmail = "Введите корректный email",
            validationPasswordTooShort = "Пароль должен содержать не менее 8 символов",
            validationPasswordsDoNotMatch = "Пароли не совпадают",
            validationAcceptTerms = "Пожалуйста, примите условия и политику",
            homeHello = "Здравствуйте,",
            scanCartQr = "Сканировать QR тележки",
            continueShopping = "Продолжить покупки",
            sessionStatusLabel = "Статус сессии",
            sessionStateWaiting = "Ожидание подтверждения",
            sessionStateConnected = "Подключено",
            sessionStateShopping = "Покупка",
            sessionStateFinished = "Сессия завершена",
            purchases = "Покупки",
            receipts = "Чеки",
            noPurchasesYet = "Покупок пока нет",
            selectLanguage = "Выберите язык",
            cancel = "Отмена",
            fullName = "Полное имя",
            fullNamePlaceholder = "Ваше полное имя",
            confirmPassword = "Подтвердите пароль",
            onboardingTitle1 = "Добро пожаловать в SmartCart",
            onboardingTitle2 = "Сканируйте QR для начала",
            onboardingTitle3 = "Оплачивайте и отслеживайте покупки",
            notificationsTitle = "Уведомления",
            notifPromoTitle = "Промокоды",
            notifPromoSubtitle = "Скидка 2000 тг на первый заказ",
            notifNewsTitle = "Новости",
            notifNewsSubtitle = "0.5 Fuse Tea = 1 тг",
            couldNotLoadHistory = "Не удалось загрузить историю покупок",
            historyAccessTemporarilyUnavailable = "Доступ временно недоступен. Попробуйте снова чуть позже.",
            historyCheckConnectionAndRetry = "Проверьте подключение и попробуйте снова.",
            orderNumberPrefix = "Заказ #",
            langKazakh = "Қазақша",
            langRussian = "Русский",
            langEnglish = "English",
            chooseLanguageSubtitle = "Тілді таңдаңыз / Выберите язык",
            productBarcodeMismatch = "Обнаружен штрихкод товара. Используйте сканер товаров.",
            legacyQrNotSupported = "Устаревший QR тележки не поддерживается. Отсканируйте QR сессии.",
            invalidCartQr = "Неверный QR код тележки",
            connectedToCart = "Подключено к",
            productNotFoundForBarcode = "Товар не найден для штрихкода",
            addedPrefix = "Добавлено",
        )

        "kk" -> AppStrings(
            email = "Электрондық пошта",
            password = "Құпиясөз",
            login = "Кіру",
            signUp = "Тіркелу",
            language = "Тіл",
            chooseLanguage = "Қосымша тілін таңдаңыз",
            personalData = "Жеке деректер",
            notifications = "Хабарламалар",
            myPurchases = "Сатып алуларым",
            myCards = "Карталарым",
            exit = "Шығу",
            user = "Пайдаланушы",
            noEmail = "Email жоқ",
            ok = "ОК",
            info = "Ақпарат",
            loading = "Жүктелуде...",
            loginWithGoogle = "Google арқылы кіру",
            dontHaveAccount = "Тіркелгіңіз жоқ па?",
            cantLogin = "Кіру мүмкін емес пе?",
            emailPlaceholder = "name@email.com",
            passwordHint = "Кемінде 8 таңба",
            goodAfternoon = "Қайырлы күн 👋🏻",
            welcomeTo = "Қош келдіңіз",
            smart = "ақылды",
            shopping = "сатып алу",
            cart = "арбасына",
            scanProduct = "Өнімді сканерлеу",
            scannerCount = "384 сканерлеу",
            receiptTaxInvoice = "Чек / салық шоты",
            detectedCount = "23 анықталды",
            productsPurchased = "Сатып алынған тауарлар",
            back = "Артқа",
            cameraPointToProduct = "Камераны тауарға бағыттаңыз",
            cameraPermissionRequired = "Камераға рұқсат қажет",
            productLabel = "Өнім",
            cartConnected = "Арба қосылды",
            cartConnectedDesc = "Телефоныңыз арбаға қосылды.",
            cartId = "Арба ID",
            notAvailable = "Қолжетімсіз",
            backToHome = "Басты бетке",
            shoppingCartTitle = "Сатып алу себеті 🛒",
            total = "Жалпы",
            currency = "TG",
            goToPayment = "Төлемге өту",
            paymentFailed = "Төлем сәтсіз аяқталды",
            userNotLoggedIn = "Пайдаланушы жүйеге кірмеген",
            receiptNotFound = "Чек табылмады",
            failedToLoadReceipt = "Чекті жүктеу мүмкін болмады",
            errorLabel = "Қате",
            shopName = "MAGNUM SHOPPING CENTER",
            receiptIdLabel = "Чек ID",
            timeLabel = "Уақыты",
            itemsLabel = "тауар",
            purchaseNotFound = "Сатып алу табылмады",
            failedToLoadPurchase = "Сатып алуды жүктеу мүмкін болмады",
            purchaseInformation = "Сатып алу туралы ақпарат",
            locationLabel = "Орналасқан жері:",
            locationValue = "Алматы, Қазақстан",
            purchaserLabel = "Сатып алушы:",
            unknown = "Белгісіз",
            dateTimeLabel = "Күні мен уақыты:",
            yourPurchase = "Сіздің сатып алуыңыз:",
            paid = "Төленді",
            amount = "Сома",
            tenge = "₸",
            history = "Тарих",
            orderCompleted = "Тапсырыстар аяқталды",
            noPurchases = "Әзірге сатып алулар жоқ",
            connectedTo = "Қосылды:",
            successful = "Сәтті аяқталды ✅",
            paymentSuccessDesc = "Төлем сәтті орындалды",
            purchaseId = "Сатып алу ID",
            downloadReceipt = "Чекті жүктеу",
            receiptUnavailable = "⚠️ Чек қолжетімсіз. purchase_id сақталғанын тексеріңіз",
            onboardingStepScanCartQr = "Сеансты бастау үшін арбадағы QR кодты сканерлеңіз",
            onboardingStepAutoAddProducts = "Сауда кезінде өнімдер автоматты түрде қосылады",
            onboardingStepInstantPay = "Кезексіз бірден төлеңіз",
            onboardingSubtitleProductFlow = "SmartCart жолы: қосылу, сауда, жылдам төлем.",
            skip = "Өткізу",
            next = "Келесі",
            start = "Бастау",
            welcomeBack = "Қош келдіңіз",
            loginSubtitleSyncCart = "Арба мен сатып алуларды синхрондау үшін кіріңіз",
            createAccount = "Тіркелгі жасау",
            signUpSubtitleEnterDetails = "Өтінеміз, деректеріңізді енгізіңіз",
            signUpWithGoogle = "Google арқылы тіркелу",
            agreeWith = "Мен",
            terms = "Шарттармен",
            privacy = "Құпиялылықпен",
            alreadyHaveAccount = "Аккаунтыңыз бар ма?",
            validationNameRequired = "Атыңыз міндетті",
            validationEnterValidEmail = "Жарамды email енгізіңіз",
            validationPasswordTooShort = "Құпиясөз кемінде 8 таңбадан тұруы керек",
            validationPasswordsDoNotMatch = "Құпиясөздер сәйкес келмейді",
            validationAcceptTerms = "Шарттар мен құпиялылықты қабылдаңыз",
            homeHello = "Сәлем,",
            scanCartQr = "Арбаның QR кодын сканерлеу",
            continueShopping = "Сауданы жалғастыру",
            sessionStatusLabel = "Сеанс күйі",
            sessionStateWaiting = "Растауды күту",
            sessionStateConnected = "Қосылды",
            sessionStateShopping = "Сауда",
            sessionStateFinished = "Сеанс аяқталды",
            purchases = "Сатып алулар",
            receipts = "Чектер",
            noPurchasesYet = "Әзірге сатып алулар жоқ",
            selectLanguage = "Тілді таңдаңыз",
            cancel = "Бас тарту",
            fullName = "Толық аты",
            fullNamePlaceholder = "Толық атыңызды енгізіңіз",
            confirmPassword = "Құпиясөзді растаңыз",
            onboardingTitle1 = "SmartCart-қа қош келдіңіз",
            onboardingTitle2 = "Бастау үшін QR сканерлеңіз",
            onboardingTitle3 = "Төлеңіз және сатып алуларды бақылаңыз",
            notificationsTitle = "Хабарламалар",
            notifPromoTitle = "Промокодтар",
            notifPromoSubtitle = "Бірінші тапсырысқа 2000 тг жеңілдік",
            notifNewsTitle = "Жаңалықтар",
            notifNewsSubtitle = "0.5 Fuse Tea = 1 тг",
            couldNotLoadHistory = "Сатып алу тарихын жүктеу мүмкін болмады",
            historyAccessTemporarilyUnavailable = "Қолжетімділік уақытша шектелген. Сәл кейінірек қайталап көріңіз.",
            historyCheckConnectionAndRetry = "Интернет қосылымын тексеріп, қайта көріңіз.",
            orderNumberPrefix = "Тапсырыс #",
            langKazakh = "Қазақша",
            langRussian = "Орысша",
            langEnglish = "English",
            chooseLanguageSubtitle = "Тілді таңдаңыз / Выберите язык",
            productBarcodeMismatch = "Өнім штрихкоды анықталды. Өнім сканерін пайдаланыңыз.",
            legacyQrNotSupported = "Ескі арба QR қолдау барылмайды. Сеанс QR сканерлеңіз.",
            invalidCartQr = "Жарамсыз арба QR коды",
            connectedToCart = "Қосылды:",
            productNotFoundForBarcode = "Бұл штрихкод бойынша тауар табылмады",
            addedPrefix = "Қосылды",
        )

        else -> AppStrings(
            email = "Email",
            password = "Password",
            login = "Log in",
            signUp = "Sign up",
            language = "Language",
            chooseLanguage = "Choose app language",
            personalData = "Personal Data",
            notifications = "Notifications",
            myPurchases = "My purchases",
            myCards = "My cards",
            exit = "Exit",
            user = "User",
            noEmail = "No email",
            ok = "OK",
            info = "Info",
            loading = "Loading...",
            loginWithGoogle = "Log in with Google",
            dontHaveAccount = "Don’t have an account?",
            cantLogin = "Can’t log in?",
            emailPlaceholder = "name@email.com",
            passwordHint = "At least 8 characters",
            goodAfternoon = "Good Afternoon 👋🏻",
            welcomeTo = "Welcome to",
            smart = "smart",
            shopping = "shopping",
            cart = "cart",
            scanProduct = "Scan a product",
            scannerCount = "384 Scanner",
            receiptTaxInvoice = "Receipt / tax invoice",
            detectedCount = "23 detected",
            productsPurchased = "Products purchased",
            back = "Back",
            cameraPointToProduct = "Point the camera at the product",
            cameraPermissionRequired = "Camera permission required",
            productLabel = "Product",
            cartConnected = "Cart Connected",
            cartConnectedDesc = "Your phone is connected to the trolley.",
            cartId = "Cart ID",
            notAvailable = "Not available",
            backToHome = "Back to Home",
            shoppingCartTitle = "Shopping Cart 🛒",
            total = "Total",
            currency = "TG",
            goToPayment = "Go To Payment",
            paymentFailed = "Payment failed",
            userNotLoggedIn = "User not logged in",
            receiptNotFound = "Receipt not found",
            failedToLoadReceipt = "Failed to load receipt",
            errorLabel = "Error",
            shopName = "MAGNUM SHOPPING CENTER",
            receiptIdLabel = "Receipt ID",
            timeLabel = "Time",
            itemsLabel = "items",
            purchaseNotFound = "Purchase not found",
            failedToLoadPurchase = "Failed to load purchase",
            purchaseInformation = "Purchase information",
            locationLabel = "Location:",
            locationValue = "Almaty, Kazakhstan",
            purchaserLabel = "Purchaser:",
            unknown = "Unknown",
            dateTimeLabel = "Date and time:",
            yourPurchase = "Your purchase:",
            paid = "Paid",
            amount = "Amount",
            tenge = "₸",
            history = "History",
            orderCompleted = "Order completed",
            noPurchases = "No purchases yet",
            connectedTo = "Connected to",
            successful = "Successful ✅",
            paymentSuccessDesc = "Your payment was completed successfully",
            purchaseId = "Purchase ID",
            downloadReceipt = "Download receipt",
            receiptUnavailable = "⚠️ Receipt unavailable. Make sure purchase_id is saved",
            onboardingStepScanCartQr = "Scan QR on cart to start session",
            onboardingStepAutoAddProducts = "Add products automatically while shopping",
            onboardingStepInstantPay = "Pay instantly without queue",
            onboardingSubtitleProductFlow = "SmartCart guides you from cart connection to instant payment.",
            skip = "Skip",
            next = "Next",
            start = "Start",
            welcomeBack = "Welcome back",
            loginSubtitleSyncCart = "Login to sync your cart and purchases",
            createAccount = "Create account",
            signUpSubtitleEnterDetails = "Please enter your details",
            signUpWithGoogle = "Sign up with Google",
            agreeWith = "I agree with",
            terms = "Terms",
            privacy = "Privacy",
            alreadyHaveAccount = "Already have an account?",
            validationNameRequired = "Name is required",
            validationEnterValidEmail = "Enter a valid email",
            validationPasswordTooShort = "Password must be at least 8 characters",
            validationPasswordsDoNotMatch = "Passwords do not match",
            validationAcceptTerms = "Please accept Terms and Privacy",
            homeHello = "Hello,",
            scanCartQr = "Scan cart QR",
            continueShopping = "Continue shopping",
            sessionStatusLabel = "Session status",
            sessionStateWaiting = "Waiting for confirmation",
            sessionStateConnected = "Connected",
            sessionStateShopping = "Shopping",
            sessionStateFinished = "Session finished",
            purchases = "Purchases",
            receipts = "Receipts",
            noPurchasesYet = "No purchases yet",
            selectLanguage = "Select language",
            cancel = "Cancel",
            fullName = "Full name",
            fullNamePlaceholder = "Your full name",
            confirmPassword = "Confirm password",
            onboardingTitle1 = "Welcome to SmartCart",
            onboardingTitle2 = "Scan QR to Start",
            onboardingTitle3 = "Pay & Track Purchases",
            notificationsTitle = "Notifications",
            notifPromoTitle = "Promocodes",
            notifPromoSubtitle = "2000tg discount for first order",
            notifNewsTitle = "News",
            notifNewsSubtitle = "0.5 fuse tea = 1tg",
            couldNotLoadHistory = "Couldn't load purchase history",
            historyAccessTemporarilyUnavailable = "Access is temporarily unavailable. Please try again shortly.",
            historyCheckConnectionAndRetry = "Please check your connection and try again.",
            orderNumberPrefix = "Order #",
            langKazakh = "Қазақша",
            langRussian = "Русский",
            langEnglish = "English",
            chooseLanguageSubtitle = "Тілді таңдаңыз / Выберите язык",
            productBarcodeMismatch = "This looks like a product barcode. Use product scanner.",
            legacyQrNotSupported = "Legacy cart QR is not supported. Scan session QR.",
            invalidCartQr = "Invalid cart/session QR",
            connectedToCart = "Connected to",
            productNotFoundForBarcode = "Product not found for barcode",
            addedPrefix = "Added",
        )
    }
}

val LocalAppStrings = staticCompositionLocalOf<AppStrings> {
    error("No AppStrings provided")
}