package com.example.smartcard.localization

import androidx.compose.runtime.staticCompositionLocalOf

data class AppStrings(
    val email: String,
    val password: String,
    val login: String,
    val signUp: String,
    val language: String,
    val chooseLanguage: String,
    val personalData: String,
    val notifications: String,
    val myPurchases: String,
    val myCards: String,
    val exit: String,
    val user: String,
    val noEmail: String,
    val ok: String,
    val info: String,
    val loading: String,
    val loginWithGoogle: String,
    val dontHaveAccount: String,
    val cantLogin: String,
    val emailPlaceholder: String,
    val passwordHint: String,
    val goodAfternoon: String,
    val welcomeTo: String,
    val smart: String,
    val shopping: String,
    val cart: String,
    val scanProduct: String,
    val scannerCount: String,
    val receiptTaxInvoice: String,
    val detectedCount: String,
    val productsPurchased: String,
    val back: String,
    val cameraPointToProduct: String,
    val cameraPermissionRequired: String,
    val productLabel: String,
    val cartConnected: String,
    val cartConnectedDesc: String,
    val cartId: String,
    val notAvailable: String,
    val backToHome: String,
    val shoppingCartTitle: String,
    val total: String,
    val currency: String,
    val goToPayment: String,
    val paymentFailed: String,
    val userNotLoggedIn: String,
    val receiptNotFound: String,
    val failedToLoadReceipt: String,
    val errorLabel: String,
    val shopName: String,
    val receiptIdLabel: String,
    val timeLabel: String,
    val itemsLabel: String,
    val purchaseNotFound: String,
    val failedToLoadPurchase: String,
    val purchaseInformation: String,
    val locationLabel: String,
    val locationValue: String,
    val purchaserLabel: String,
    val unknown: String,
    val dateTimeLabel: String,
    val yourPurchase: String,
    val paid: String,
    val amount: String,
    val tenge: String,
    val history: String,
    val orderCompleted: String,
    val noPurchases: String,
    val connectedTo: String,
    val successful: String,
    val paymentSuccessDesc: String,
    val purchaseId: String,
    val downloadReceipt: String,
    val receiptUnavailable: String,
)

fun provideStrings(lang: String): AppStrings {
    return when (lang) {

        "ru" -> AppStrings(
            email = "Электронная почта",
            password = "Пароль",
            login = "Войти",
            signUp = "Зарегистрироваться",
            language = "Язык",
            chooseLanguage = "Выберите язык приложения",
            personalData = "Личные данные",
            notifications = "Уведомления",
            myPurchases = "Мои покупки",
            myCards = "Мои карты",
            exit = "Выйти",
            user = "Пользователь",
            noEmail = "Нет email",
            ok = "ОК",
            info = "Информация",
            loading = "Загрузка...",
            loginWithGoogle = "Войти через Google",
            dontHaveAccount = "Нет аккаунта?",
            cantLogin = "Не удаётся войти?",
            emailPlaceholder = "name@email.com",
            passwordHint = "Минимум 8 символов",
            goodAfternoon = "Добрый день 👋🏻",
            welcomeTo = "ДОБРО ПОЖАЛОВАТЬ В",
            smart = "умную",
            shopping = "покупательскую",
            cart = "корзину",
            scanProduct = "Сканировать товар",
            scannerCount = "384 сканирований",
            receiptTaxInvoice = "Чек / налоговая накладная",
            detectedCount = "Обнаружено 23",
            productsPurchased = "Купленные товары",
            back = "Назад",
            cameraPointToProduct = "Наведите камеру на товар",
            cameraPermissionRequired = "Требуется разрешение на камеру",
            productLabel = "Товар",
            cartConnected = "Тележка подключена",
            cartConnectedDesc = "Ваш телефон подключен к тележке.",
            cartId = "ID тележки",
            notAvailable = "Недоступно",
            backToHome = "На главную",
            shoppingCartTitle = "Корзина покупок 🛒",
            total = "Итого",
            currency = "TG",
            goToPayment = "Перейти к оплате",
            paymentFailed = "Оплата не удалась",
            userNotLoggedIn = "Пользователь не вошёл в систему",
            receiptNotFound = "Чек не найден",
            failedToLoadReceipt = "Не удалось загрузить чек",
            errorLabel = "Ошибка",
            shopName = "MAGNUM SHOPPING CENTER",
            receiptIdLabel = "ID чека",
            timeLabel = "Время",
            itemsLabel = "товаров",
            purchaseNotFound = "Покупка не найдена",
            failedToLoadPurchase = "Не удалось загрузить покупку",
            purchaseInformation = "Информация о покупке",
            locationLabel = "Местоположение:",
            locationValue = "Алматы, Казахстан",
            purchaserLabel = "Покупатель:",
            unknown = "Неизвестно",
            dateTimeLabel = "Дата и время:",
            yourPurchase = "Ваша покупка:",
            paid = "Оплачено",
            amount = "Сумма",
            tenge = "₸",
            history = "История",
            orderCompleted = "Заказы завершены",
            noPurchases = "Покупок пока нет",
            connectedTo = "Подключено к",
            successful = "Успешно ✅",
            paymentSuccessDesc = "Ваш платеж успешно завершён",
            purchaseId = "ID покупки",
            downloadReceipt = "Скачать чек",
            receiptUnavailable = "⚠️ Чек недоступен. Проверьте сохранение purchase_id",
        )

        "kk" -> AppStrings(
            email = "Электрондық пошта",
            password = "Құпиясөз",
            login = "Кіру",
            signUp = "Тіркелу",
            language = "Тіл",
            chooseLanguage = "Қосымша тілін таңдаңыз",
            personalData = "Жеке деректер",
            notifications = "Хабарламалар",
            myPurchases = "Сатып алуларым",
            myCards = "Карталарым",
            exit = "Шығу",
            user = "Пайдаланушы",
            noEmail = "Email жоқ",
            ok = "ОК",
            info = "Ақпарат",
            loading = "Жүктелуде...",
            loginWithGoogle = "Google арқылы кіру",
            dontHaveAccount = "Тіркелгіңіз жоқ па?",
            cantLogin = "Кіру мүмкін емес пе?",
            emailPlaceholder = "name@email.com",
            passwordHint = "Кемінде 8 таңба",
            goodAfternoon = "Қайырлы күн 👋🏻",
            welcomeTo = "ҚОШ КЕЛДІҢІЗ",
            smart = "ақылды",
            shopping = "сатып алу",
            cart = "арбасына",
            scanProduct = "Өнімді сканерлеу",
            scannerCount = "384 сканерлеу",
            receiptTaxInvoice = "Чек / салық шоты",
            detectedCount = "23 анықталды",
            productsPurchased = "Сатып алынған тауарлар",
            back = "Артқа",
            cameraPointToProduct = "Камераны тауарға бағыттаңыз",
            cameraPermissionRequired = "Камераға рұқсат қажет",
            productLabel = "Өнім",
            cartConnected = "Арба қосылды",
            cartConnectedDesc = "Телефоныңыз арбаға қосылды.",
            cartId = "Арба ID",
            notAvailable = "Қолжетімсіз",
            backToHome = "Басты бетке",
            shoppingCartTitle = "Сатып алу себеті 🛒",
            total = "Жалпы",
            currency = "TG",
            goToPayment = "Төлемге өту",
            paymentFailed = "Төлем сәтсіз аяқталды",
            userNotLoggedIn = "Пайдаланушы жүйеге кірмеген",
            receiptNotFound = "Чек табылмады",
            failedToLoadReceipt = "Чекті жүктеу мүмкін болмады",
            errorLabel = "Қате",
            shopName = "MAGNUM SHOPPING CENTER",
            receiptIdLabel = "Чек ID",
            timeLabel = "Уақыты",
            itemsLabel = "тауар",
            purchaseNotFound = "Сатып алу табылмады",
            failedToLoadPurchase = "Сатып алуды жүктеу мүмкін болмады",
            purchaseInformation = "Сатып алу туралы ақпарат",
            locationLabel = "Орналасқан жері:",
            locationValue = "Алматы, Қазақстан",
            purchaserLabel = "Сатып алушы:",
            unknown = "Белгісіз",
            dateTimeLabel = "Күні мен уақыты:",
            yourPurchase = "Сіздің сатып алуыңыз:",
            paid = "Төленді",
            amount = "Сома",
            tenge = "₸",
            history = "Тарих",
            orderCompleted = "Тапсырыстар аяқталды",
            noPurchases = "Әзірге сатып алулар жоқ",
            connectedTo = "Қосылды:",
            successful = "Сәтті аяқталды ✅",
            paymentSuccessDesc = "Төлем сәтті орындалды",
            purchaseId = "Сатып алу ID",
            downloadReceipt = "Чекті жүктеу",
            receiptUnavailable = "⚠️ Чек қолжетімсіз. purchase_id сақталғанын тексеріңіз",
        )

        else -> AppStrings(
            email = "Email",
            password = "Password",
            login = "Log in",
            signUp = "Sign up",
            language = "Language",
            chooseLanguage = "Choose app language",
            personalData = "Personal Data",
            notifications = "Notifications",
            myPurchases = "My purchases",
            myCards = "My cards",
            exit = "Exit",
            user = "User",
            noEmail = "No email",
            ok = "OK",
            info = "Info",
            loading = "Loading...",
            loginWithGoogle = "Log in with Google",
            dontHaveAccount = "Don’t have an account?",
            cantLogin = "Can’t log in?",
            emailPlaceholder = "name@email.com",
            passwordHint = "At least 8 characters",
            goodAfternoon = "Good Afternoon 👋🏻",
            welcomeTo = "WELCOME TO",
            smart = "smart",
            shopping = "shopping",
            cart = "cart",
            scanProduct = "Scan a product",
            scannerCount = "384 Scanner",
            receiptTaxInvoice = "Receipt / tax invoice",
            detectedCount = "23 detected",
            productsPurchased = "Products purchased",
            back = "Back",
            cameraPointToProduct = "Point the camera at the product",
            cameraPermissionRequired = "Camera permission required",
            productLabel = "Product",
            cartConnected = "Cart Connected",
            cartConnectedDesc = "Your phone is connected to the trolley.",
            cartId = "Cart ID",
            notAvailable = "Not available",
            backToHome = "Back to Home",
            shoppingCartTitle = "Shopping Cart 🛒",
            total = "Total",
            currency = "TG",
            goToPayment = "Go To Payment",
            paymentFailed = "Payment failed",
            userNotLoggedIn = "User not logged in",
            receiptNotFound = "Receipt not found",
            failedToLoadReceipt = "Failed to load receipt",
            errorLabel = "Error",
            shopName = "MAGNUM SHOPPING CENTER",
            receiptIdLabel = "Receipt ID",
            timeLabel = "Time",
            itemsLabel = "items",
            purchaseNotFound = "Purchase not found",
            failedToLoadPurchase = "Failed to load purchase",
            purchaseInformation = "Purchase information",
            locationLabel = "Location:",
            locationValue = "Almaty, Kazakhstan",
            purchaserLabel = "Purchaser:",
            unknown = "Unknown",
            dateTimeLabel = "Date and time:",
            yourPurchase = "Your purchase:",
            paid = "Paid",
            amount = "Amount",
            tenge = "₸",
            history = "History",
            orderCompleted = "Order completed",
            noPurchases = "No purchases yet",
            connectedTo = "Connected to",
            successful = "Successful ✅",
            paymentSuccessDesc = "Your payment was completed successfully",
            purchaseId = "Purchase ID",
            downloadReceipt = "Download receipt",
            receiptUnavailable = "⚠️ Receipt unavailable. Make sure purchase_id is saved",
        )
    }
}

val LocalAppStrings = staticCompositionLocalOf<AppStrings> {
    error("No AppStrings provided")
}